AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  collie-smart-tv-webpage
  
  Hosting estático para la web de App TV (S3 + CloudFront)

Parameters:
  AppDomainName:
    Type: String
    Description: Dominio completo de la aplicación (ej. stage.apptv.com.ar o www.apptv.com.ar)
  CertificateArn:
    Type: String
    Description: ARN del certificado ACM en us-east-1 para el dominio (Dejar en blanco si no se usa HTTPS personalizado por ahora/para dev)
    Default: ""

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref AppDomainName, ""]]
  HasCertificate: !Not [!Equals [!Ref CertificateArn, ""]]

Resources:
  # Bucket S3 para el contenido estático
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppDomainName}-content
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # CloudFront Origin Access Identity para restringir acceso al bucket solo a CF
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AppDomainName}"

  # Política del Bucket para permitir lectura desde CloudFront
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  # Distribución de CloudFront
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: !Sub "S3-${WebsiteBucket}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        
        Enabled: true
        DefaultRootObject: index.html
        
        # Si tenemos dominio y certificado, configurar Aliases y ViewerCertificate
        Aliases: 
          Fn::If: 
            - HasCustomDomain
            - [!Ref AppDomainName]
            - !Ref "AWS::NoValue"
            
        ViewerCertificate:
          Fn::If:
            - HasCertificate
            - AcmCertificateArn: !Ref CertificateArn
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            - CloudFrontDefaultCertificate: true

        DefaultCacheBehavior:
          AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
          CachedMethods: ['GET', 'HEAD', 'OPTIONS']
          TargetOriginId: !Sub "S3-${WebsiteBucket}"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
          Compress: true

        # Custom Error Response para SPA (opcional, útil si cambiamos a React Router en el futuro)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  WebsiteURL:
    Description: URL de CloudFront
    Value: !GetAtt WebsiteDistribution.DomainName
  BucketName:
    Description: Nombre del Bucket S3 de origen
    Value: !Ref WebsiteBucket
